{% set dev_card="- !include dev_card.yaml" %}

title: Åvägen
resources: !include resources.yaml
views:
  - title: Hemma
    cards:
      - !include floorplan.yaml
      - !include coffee_card.yaml
      - !include cameras/barnrum.yaml
      - !include cameras/kontor.yaml
      {{ dev_card }}

  - title: Floorplan
    panel: true
    cards:
      - type: vertical-stack
        cards:
        - !include floorplan.yaml
        {{ dev_card }}
