{% set dev_card="- !include dev_card.yaml" %}

title: Åvägen
resources:
  - url: !file /local/lovelace-card-tools/card-tools.js
    type: js
  - url: !file /local/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: !file /local/lovelace-time-input-row/time-input-row.js
    type: js
views:
  - title: Hemma
    cards:
      - !include floorplan.yaml
      - !include coffee_card.yaml
      - !include cameras/barnrum.yaml
      {{ dev_card }}

  - title: Floorplan
    panel: true
    cards:
      - type: vertical-stack
        cards:
        - !include floorplan.yaml
        {{ dev_card }}
