homeassistant:
  name: Åvägen

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  time_zone: !secret timezone_home
  unit_system: metric

  # Everything important is here
  packages: !include_dir_named packages

discovery:
frontend:
recorder:
  db_url: !secret db_url
history:
logbook:
config:

http:
  # mydomain.com:443 - proxied by nginx to port 8123
  base_url: !secret base_url
  api_password: !secret api_password
