homeassistant:
  name: Åvägen

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  time_zone: !secret timezone_home
  unit_system: metric

  packages: !include_dir_named packages

frontend:
discovery:
history:
logbook:
config:

http:
  base_url: !secret base_url
  api_password: !secret api_password
