homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "cameras"
        hidden: true

    input_number.appd_dummy:
      <<: *common
    input_datetime.appd_dummy:
      <<: *common
    input_select.appd_dummy:
      <<: *common
    input_boolean.appd_dummy:
      <<: *common
    input_text.appd_dummy:
      <<: *common

# Those things do nothing and will never be seen
# Their only purpose is to make sure the services used to controll the corresponding entity types are loaded.
input_number:
  appd_dummy:
    min: 0
    max: 10
input_datetime:
  appd_dummy:
    has_date: False
    has_time: True
input_select:
  appd_dummy:
    options: [1]
input_boolean:
  appd_dummy:
input_text:
  appd_dummy:
    name: dummy
    initial: dummy
