homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "lights"
      grouped: &grouped
        hidden: true

    light.sovrum:
      <<: *common
    light.sovrum1:
      <<: *grouped
    light.sovrum2:
      <<: *grouped
    light.sovrum3:
      <<: *grouped

    light.takfläkt:
      <<: *common
    light.takflakt_1:
      <<: *grouped
    light.takflakt_2:
      <<: *grouped
    light.takflakt_3:
      <<: *grouped
    light.takflakt_4:
      <<: *grouped

light:
  - platform: group
    name: Sovrum
    entities:
      - light.sovrum1
      - light.sovrum2
      - light.sovrum3
  - platform: group
    name: Takfläkt
    entities:
      - light.takflakt_1
      - light.takflakt_2
      - light.takflakt_3
      - light.takflakt_4
