homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: 'reminders'

automation:
  - alias: REM - Kaffet är klart
    initial_state: True
    trigger:
      platform: state
      entity_id: switch.kaffebryggare
      to: 'on'
      for:
        minutes: 5
    action:
      - service: notify.ios_thomas_iphone
        data:
          title: "Fikadax!"
          message: "Kaffet är färdigt!"
